require:
  - rubocop/cop/github/accessibility

GitHub/Accessibility/ImageHasAlt:
  Enabled: true
  StyleGuide: https://github.com/github/rubocop-github/blob/master/guides/image-has-alt.md
GitHub/Accessibility/LinkHasHref:
  Enabled: true
  StyleGuide: https://github.com/github/rubocop-github/blob/master/guides/link-has-href.md